"""Add timestamp columns to bekpacktrip

Revision ID: 1acba1561825
Revises: d89db0bd7dc0
Create Date: 2021-01-12 05:06:05.730570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acba1561825'
down_revision = 'd89db0bd7dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bekpacktrip', sa.Column('time_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('bekpacktrip', sa.Column('time_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bekpacktrip', 'time_updated')
    op.drop_column('bekpacktrip', 'time_created')
    # ### end Alembic commands ###
