"""Add BekpackTrip.Color column

Revision ID: 4b166de0073e
Revises: 4e78bbcfad8d
Create Date: 2020-12-25 06:10:19.192082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b166de0073e'
down_revision = '4e78bbcfad8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bekpackbag', sa.Column('color', sa.String(), nullable=True))
    op.add_column('bekpacktrip', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bekpacktrip', 'color')
    op.drop_column('bekpackbag', 'color')
    # ### end Alembic commands ###
