"""Remove BekpackTrip.Color column

Revision ID: 4e78bbcfad8d
Revises: b921a490461d
Create Date: 2020-12-25 06:09:33.129316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e78bbcfad8d"
down_revision = "b921a490461d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bekpackbag", "color")
    op.drop_column("bekpacktrip", "color")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bekpacktrip",
        sa.Column("color", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.add_column(
        "bekpackbag",
        sa.Column("color", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
