"""Create BekPack models

Revision ID: 6903969336a4
Revises: d4867f3a4c0a
Create Date: 2020-12-24 05:23:43.395276

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "6903969336a4"
down_revision = "d4867f3a4c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bekpackuser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bekpackuser_id"), "bekpackuser", ["id"], unique=False)
    op.create_table(
        "bekpacktrip",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "color", sqlalchemy_utils.types.color.ColorType(length=20), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["bekpackuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bekpacktrip_id"), "bekpacktrip", ["id"], unique=False)
    op.create_index(op.f("ix_bekpacktrip_name"), "bekpacktrip", ["name"], unique=False)
    op.create_index(
        op.f("ix_bekpacktrip_owner_id"), "bekpacktrip", ["owner_id"], unique=False
    )
    op.create_table(
        "bekpackbag",
        sa.Column(
            "color", sqlalchemy_utils.types.color.ColorType(length=20), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("owner_trip_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["bekpackuser.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_trip_id"],
            ["bekpacktrip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bekpackbag_id"), "bekpackbag", ["id"], unique=False)
    op.create_index(
        op.f("ix_bekpackbag_owner_id"), "bekpackbag", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_bekpackbag_owner_trip_id"),
        "bekpackbag",
        ["owner_trip_id"],
        unique=False,
    )
    op.create_table(
        "bekpacktrip_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["bekpacktrip.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bekpackuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bekpacktrip_members_trip_id"),
        "bekpacktrip_members",
        ["trip_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bekpacktrip_members_user_id"),
        "bekpacktrip_members",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "bekpacktripitemlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("parent_trip_id", sa.Integer(), nullable=True),
        sa.Column("parent_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_trip_id"], ["bekpacktrip.id"], ondelete="cascade"
        ),
        sa.ForeignKeyConstraint(
            ["parent_user_id"], ["bekpackuser.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id", "parent_user_id"),
    )
    op.create_index(
        op.f("ix_bekpacktripitemlist_id"), "bekpacktripitemlist", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_bekpacktripitemlist_parent_trip_id"),
        "bekpacktripitemlist",
        ["parent_trip_id"],
        unique=False,
    )
    op.create_table(
        "bekpacklistitem",
        sa.Column("bag_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("list_index", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("parent_list_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bag_id"],
            ["bekpackbag.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_list_id"], ["bekpacktripitemlist.id"], ondelete="cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bekpacklistitem_id"), "bekpacklistitem", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_bekpacklistitem_parent_list_id"),
        "bekpacklistitem",
        ["parent_list_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bekpacklistitem_parent_list_id"), table_name="bekpacklistitem"
    )
    op.drop_index(op.f("ix_bekpacklistitem_id"), table_name="bekpacklistitem")
    op.drop_table("bekpacklistitem")
    op.drop_index(
        op.f("ix_bekpacktripitemlist_parent_trip_id"), table_name="bekpacktripitemlist"
    )
    op.drop_index(op.f("ix_bekpacktripitemlist_id"), table_name="bekpacktripitemlist")
    op.drop_table("bekpacktripitemlist")
    op.drop_index(
        op.f("ix_bekpacktrip_members_user_id"), table_name="bekpacktrip_members"
    )
    op.drop_index(
        op.f("ix_bekpacktrip_members_trip_id"), table_name="bekpacktrip_members"
    )
    op.drop_table("bekpacktrip_members")
    op.drop_index(op.f("ix_bekpackbag_owner_trip_id"), table_name="bekpackbag")
    op.drop_index(op.f("ix_bekpackbag_owner_id"), table_name="bekpackbag")
    op.drop_index(op.f("ix_bekpackbag_id"), table_name="bekpackbag")
    op.drop_table("bekpackbag")
    op.drop_index(op.f("ix_bekpacktrip_owner_id"), table_name="bekpacktrip")
    op.drop_index(op.f("ix_bekpacktrip_name"), table_name="bekpacktrip")
    op.drop_index(op.f("ix_bekpacktrip_id"), table_name="bekpacktrip")
    op.drop_table("bekpacktrip")
    op.drop_index(op.f("ix_bekpackuser_id"), table_name="bekpackuser")
    op.drop_table("bekpackuser")
    # ### end Alembic commands ###
