"""Create BekpakUser, BekpakTrip

Revision ID: 6e662bb3bd80
Revises: d4867f3a4c0a
Create Date: 2020-12-22 06:00:06.237658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e662bb3bd80'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bekpackuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bekpackuser_id'), 'bekpackuser', ['id'], unique=False)
    op.create_table('bekpacktrip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('color', sqlalchemy_utils.types.color.ColorType(length=20), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['bekpackuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bekpacktrip_id'), 'bekpacktrip', ['id'], unique=False)
    op.create_index(op.f('ix_bekpacktrip_name'), 'bekpacktrip', ['name'], unique=False)
    op.create_table('bekpackbag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_trip_id', sa.Integer(), nullable=True),
    sa.Column('color', sqlalchemy_utils.types.color.ColorType(length=20), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['bekpackuser.id'], ),
    sa.ForeignKeyConstraint(['owner_trip_id'], ['bekpacktrip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bekpackbag_id'), 'bekpackbag', ['id'], unique=False)
    op.create_index(op.f('ix_bekpackbag_owner_id'), 'bekpackbag', ['owner_id'], unique=False)
    op.create_index(op.f('ix_bekpackbag_owner_trip_id'), 'bekpackbag', ['owner_trip_id'], unique=False)
    op.create_table('bekpacktrip_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['bekpacktrip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['bekpackuser.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'trip_id')
    )
    op.create_index(op.f('ix_bekpacktrip_members_trip_id'), 'bekpacktrip_members', ['trip_id'], unique=False)
    op.create_index(op.f('ix_bekpacktrip_members_user_id'), 'bekpacktrip_members', ['user_id'], unique=False)
    op.create_table('bekpacktripitemlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_trip', sa.Integer(), nullable=False),
    sa.Column('parent_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_trip'], ['bekpacktrip.id'], ),
    sa.ForeignKeyConstraint(['parent_user'], ['bekpackuser.id'], ),
    sa.PrimaryKeyConstraint('id', 'parent_trip', 'parent_user')
    )
    op.create_index(op.f('ix_bekpacktripitemlist_id'), 'bekpacktripitemlist', ['id'], unique=False)
    op.create_table('bekpacklistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=True),
    sa.Column('parent_list', sa.Integer(), nullable=True),
    sa.Column('list_index', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bag_id'], ['bekpackbag.id'], ),
    sa.ForeignKeyConstraint(['parent_list'], ['bekpacktripitemlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bekpacklistitem_id'), 'bekpacklistitem', ['id'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_bekpacklistitem_id'), table_name='bekpacklistitem')
    op.drop_table('bekpacklistitem')
    op.drop_index(op.f('ix_bekpacktripitemlist_id'), table_name='bekpacktripitemlist')
    op.drop_table('bekpacktripitemlist')
    op.drop_index(op.f('ix_bekpacktrip_members_user_id'), table_name='bekpacktrip_members')
    op.drop_index(op.f('ix_bekpacktrip_members_trip_id'), table_name='bekpacktrip_members')
    op.drop_table('bekpacktrip_members')
    op.drop_index(op.f('ix_bekpackbag_owner_trip_id'), table_name='bekpackbag')
    op.drop_index(op.f('ix_bekpackbag_owner_id'), table_name='bekpackbag')
    op.drop_index(op.f('ix_bekpackbag_id'), table_name='bekpackbag')
    op.drop_table('bekpackbag')
    op.drop_index(op.f('ix_bekpacktrip_name'), table_name='bekpacktrip')
    op.drop_index(op.f('ix_bekpacktrip_id'), table_name='bekpacktrip')
    op.drop_table('bekpacktrip')
    op.drop_index(op.f('ix_bekpackuser_id'), table_name='bekpackuser')
    op.drop_table('bekpackuser')
    # ### end Alembic commands ###
