"""Bekpack foreign keys

Revision ID: 876b72adef4a
Revises: 4b166de0073e
Create Date: 2021-01-07 06:37:49.875965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "876b72adef4a"
down_revision = "4b166de0073e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bekpackbag_owner_id_fkey", "bekpackbag", type_="foreignkey")
    op.drop_constraint(
        "bekpackbag_owner_trip_id_fkey", "bekpackbag", type_="foreignkey"
    )
    op.create_foreign_key(
        "bekpackbag_owner_id_fkey",
        "bekpackbag",
        "bekpacktrip",
        ["owner_trip_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "bekpackbag_owner_trip_id_fkey",
        "bekpackbag",
        "bekpackuser",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("bekpacktrip_owner_id_fkey", "bekpacktrip", type_="foreignkey")
    op.create_foreign_key(
        "bekpacktrip_owner_id_fkey",
        "bekpacktrip",
        "bekpackuser",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "bekpacktrip_members_trip_id_fkey", "bekpacktrip_members", type_="foreignkey"
    )
    op.drop_constraint(
        "bekpacktrip_members_user_id_fkey", "bekpacktrip_members", type_="foreignkey"
    )
    op.create_foreign_key(
        "bekpacktrip_members_user_id_fkey",
        "bekpacktrip_members",
        "bekpackuser",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "bekpacktrip_members_trip_id_fkey",
        "bekpacktrip_members",
        "bekpacktrip",
        ["trip_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("bekpackuser_owner_id_fkey", "bekpackuser", type_="foreignkey")
    op.create_foreign_key(
        "bekpackuser_owner_id_fkey",
        "bekpackuser",
        "user",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bekpackuser_owner_id_fkey", "bekpackuser", type_="foreignkey")
    op.create_foreign_key(
        "bekpackuser_owner_id_fkey", "bekpackuser", "user", ["owner_id"], ["id"]
    )
    op.drop_constraint(
        "bekpacktrip_members_user_id_fkey", "bekpacktrip_members", type_="foreignkey"
    )
    op.drop_constraint(
        "bekpacktrip_members_trip_id_fkey", "bekpacktrip_members", type_="foreignkey"
    )
    op.create_foreign_key(
        "bekpacktrip_members_user_id_fkey",
        "bekpacktrip_members",
        "bekpackuser",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "bekpacktrip_members_trip_id_fkey",
        "bekpacktrip_members",
        "bekpacktrip",
        ["trip_id"],
        ["id"],
    )
    op.drop_constraint("bekpacktrip_owner_id_fkey", "bekpacktrip", type_="foreignkey")
    op.create_foreign_key(
        "bekpacktrip_owner_id_fkey", "bekpacktrip", "bekpackuser", ["owner_id"], ["id"]
    )
    op.drop_constraint(
        "bekpackbag_owner_trip_id_fkey", "bekpackbag", type_="foreignkey"
    )
    op.drop_constraint("bekpackbag_owner_id_fkey", "bekpackbag", type_="foreignkey")
    op.create_foreign_key(
        "bekpackbag_owner_trip_id_fkey",
        "bekpackbag",
        "bekpacktrip",
        ["owner_trip_id"],
        ["id"],
    )
    op.create_foreign_key(
        "bekpackbag_owner_id_fkey", "bekpackbag", "bekpackuser", ["owner_id"], ["id"]
    )
    # ### end Alembic commands ###
