"""Fix bekpackUser owners not unique

Revision ID: b921a490461d
Revises: 655382d7edaa
Create Date: 2020-12-25 01:22:01.513348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b921a490461d"
down_revision = "655382d7edaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "bekpackuser_owner_id_unique", "bekpackuser", ["owner_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint("bekpackuser_owner_id_unique", "bekpackuser", type_="unique")
    except:
        pass
    # ### end Alembic commands ###
