"""Add timestamp columns to bekpacktrip

Revision ID: cccf2dd17a0b
Revises: d89db0bd7dc0
Create Date: 2021-01-12 07:19:45.476362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccf2dd17a0b'
down_revision = 'd89db0bd7dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bekpacktrip', sa.Column('time_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('bekpacktrip', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bekpacktrip_time_created'), 'bekpacktrip', ['time_created'], unique=False)
    op.create_index(op.f('ix_bekpacktrip_time_updated'), 'bekpacktrip', ['time_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bekpacktrip_time_updated'), table_name='bekpacktrip')
    op.drop_index(op.f('ix_bekpacktrip_time_created'), table_name='bekpacktrip')
    op.drop_column('bekpacktrip', 'time_updated')
    op.drop_column('bekpacktrip', 'time_created')
    # ### end Alembic commands ###
