"""bekpacktrip add description

Revision ID: d89db0bd7dc0
Revises: 876b72adef4a
Create Date: 2021-01-09 04:46:22.121876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89db0bd7dc0'
down_revision = '876b72adef4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bekpacktrip', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bekpacktrip', 'description')
    # ### end Alembic commands ###
